### PR TITLE
added swiper.parallax and swiper.navigation

### PR DESCRIPTION
**Pull request by BananaAcid**
added capabilities from its Framework7 alternative like parallax, navigation arrows.
fixed some logic problems.
updated readme.
changed some unusual handling (in example js)

see here: [https://myvoyagemap.com/x-ws-test-2](https://myvoyagemap.com/x-ws-test-2)

### CODE REVIEW

**Comment by BananaAcid** [comment]
Done reworking it.

**Comment by BananaAcid** [comment]
Helps with issue https://github.com/valnub/welcomescreen.js/issues/5 and https://github.com/valnub/welcomescreen.js/issues/4 as well

**Comment by valnub** [comment]
Thanks, merged but did a small mod to it: https://github.com/valnub/welcomescreen.js/commit/5f68c0c0d231f7da6559667dad9f441c447ac4c1

If `//` is used for all references then opening via `file:///` won't work.

**Comment by BananaAcid** [comment]
Thats true - i just thought about supporting http/https in local dev and PWAs as well as https restricted connections (WLAN on hotels, airplane).

**Pull request merged**
